/*
 * About.java
 *
 * Created on 15 de Março de 2008, 18:01
 */

package de.berlios.kcookb.gui;

import java.io.IOException;
import javax.swing.JEditorPane;

/**
 *
 * @author  Knitter
 */
public class About extends javax.swing.JDialog {
    
    /** Creates new form About */
    public About(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadLicense();
    }
    
    private void loadLicense() {
    }
    
    public void showCentered() {
        setLocation(getParent().getX() + (getParent().getWidth() / 2) - (getWidth() / 2),
                getParent().getY() + (getParent().getHeight() / 2) - (getHeight() / 2));
        setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtbpAbout = new javax.swing.JTabbedPane();
        jpLogo = new javax.swing.JPanel();
        jlblLogo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDetails = new javax.swing.JTextArea();
        jpLicense = new javax.swing.JPanel();
        jscpLicense = new javax.swing.JScrollPane();
        try {
            jepLicense = new JEditorPane(getClass().getResource("/de/berlios/kcookb/resources/gpl-2.0.txt"));
        } catch(IOException ex) {
            ex.printStackTrace();
        }

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/berlios/kcookb/resources/languages/language"); // NOI18N
        setTitle(bundle.getString("ABOUTDIALOG_TITLE")); // NOI18N
        setResizable(false);

        jlblLogo.setText("jLabel1");

        jtaDetails.setBackground(new java.awt.Color(236, 233, 216));
        jtaDetails.setColumns(20);
        jtaDetails.setRows(5);
        jScrollPane1.setViewportView(jtaDetails);

        javax.swing.GroupLayout jpLogoLayout = new javax.swing.GroupLayout(jpLogo);
        jpLogo.setLayout(jpLogoLayout);
        jpLogoLayout.setHorizontalGroup(
            jpLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                    .addComponent(jlblLogo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpLogoLayout.setVerticalGroup(
            jpLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtbpAbout.addTab(bundle.getString("ABOUTDIALOG_LOGOTAB_TITLE"), jpLogo); // NOI18N

        jepLicense.setEditable(false);
        jscpLicense.setViewportView(jepLicense);

        javax.swing.GroupLayout jpLicenseLayout = new javax.swing.GroupLayout(jpLicense);
        jpLicense.setLayout(jpLicenseLayout);
        jpLicenseLayout.setHorizontalGroup(
            jpLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLicenseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jscpLicense, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpLicenseLayout.setVerticalGroup(
            jpLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLicenseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jscpLicense, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtbpAbout.addTab(bundle.getString("ABOUTDIALOG_LICENSETAB_TITLE"), jpLicense); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtbpAbout, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtbpAbout, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JEditorPane jepLicense;
    private javax.swing.JLabel jlblLogo;
    private javax.swing.JPanel jpLicense;
    private javax.swing.JPanel jpLogo;
    private javax.swing.JScrollPane jscpLicense;
    private javax.swing.JTextArea jtaDetails;
    private javax.swing.JTabbedPane jtbpAbout;
    // End of variables declaration//GEN-END:variables
    
}
