/*
 * BookInfoGui.java
 *
 * Created on 15 de Março de 2008, 18:01
 */
package de.berlios.kcookb.gui;

import de.berlios.kcookb.model.BookInfo;
import de.berlios.kcookb.model.KCookB;
import java.util.Date;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author  Knitter
 */
public class BookInfoGui extends javax.swing.JDialog {

    private KCookB book;
    private boolean dirty;

    /** Creates new form BookInfoGui */
    public BookInfoGui(java.awt.Frame parent, boolean modal, KCookB book) {
        super(parent, modal);
        this.book = book;
        initComponents();

        //Listeners to changes on the interface.
        jtfEmail.getDocument().addDocumentListener(new DocumentListener() {

            public void insertUpdate(DocumentEvent e) {
                dirty = true;
            }

            public void removeUpdate(DocumentEvent e) {
                dirty = true;
            }

            public void changedUpdate(DocumentEvent e) {
                dirty = true;
            }
        });

        jtfName.getDocument().addDocumentListener(new DocumentListener() {

            public void insertUpdate(DocumentEvent e) {
                dirty = true;
            }

            public void removeUpdate(DocumentEvent e) {
                dirty = true;
            }

            public void changedUpdate(DocumentEvent e) {
                dirty = true;
            }
        });

        //Setting initial date value.
        //Maybe move this code to the init method.
        Date d = this.book.getInfo().getCreated();
        jdcCreatedOn.setDate(d != null ? d : new Date());
    }

    public void showCentered() {
        setLocation(getParent().getX() + (getParent().getWidth() / 2) - (getWidth() / 2),
                getParent().getY() + (getParent().getHeight() / 2) - (getHeight() / 2));
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCatalogInfo = new javax.swing.JPanel();
        jlblAuthorName = new javax.swing.JLabel();
        jtfName = new JTextField(book.getInfo().getAuthor());
        jtfEmail = new JTextField(book.getInfo().getEmail());
        jlblAuthorEmail = new javax.swing.JLabel();
        jlblCreatedOn = new javax.swing.JLabel();
        jdcCreatedOn = new com.toedter.calendar.JDateChooser();
        jbtnCancel = new javax.swing.JButton();
        jbtnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("null");
        setResizable(false);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/berlios/kcookb/resources/i18n/i18n"); // NOI18N
        jpCatalogInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("BOOKINFODIALOG_BORDER"))); // NOI18N

        jlblAuthorName.setText(bundle.getString("BookInfoGui.jlblAuthorName.text")); // NOI18N

        jlblAuthorEmail.setText(bundle.getString("BookInfoGui.jlblAuthorEmail.text")); // NOI18N

        jlblCreatedOn.setText(bundle.getString("BookInfoGui.jlblCreatedOn.text")); // NOI18N

        jdcCreatedOn.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jdcCreatedOnPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jpCatalogInfoLayout = new javax.swing.GroupLayout(jpCatalogInfo);
        jpCatalogInfo.setLayout(jpCatalogInfoLayout);
        jpCatalogInfoLayout.setHorizontalGroup(
            jpCatalogInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCatalogInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCatalogInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCatalogInfoLayout.createSequentialGroup()
                        .addGroup(jpCatalogInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblAuthorName)
                            .addComponent(jlblAuthorEmail))
                        .addGap(38, 38, 38)
                        .addGroup(jpCatalogInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                            .addComponent(jtfName, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)))
                    .addGroup(jpCatalogInfoLayout.createSequentialGroup()
                        .addComponent(jlblCreatedOn)
                        .addGap(18, 18, 18)
                        .addComponent(jdcCreatedOn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpCatalogInfoLayout.setVerticalGroup(
            jpCatalogInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCatalogInfoLayout.createSequentialGroup()
                .addGroup(jpCatalogInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblAuthorName)
                    .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCatalogInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblAuthorEmail)
                    .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCatalogInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblCreatedOn)
                    .addComponent(jdcCreatedOn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jbtnCancel.setText(bundle.getString("BookInfoGui.jbtnCancel.text")); // NOI18N
        jbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelActionPerformed(evt);
            }
        });

        jbtnSave.setText(bundle.getString("BookInfoGui.jbtnSave.text")); // NOI18N
        jbtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnCancel))
                    .addComponent(jpCatalogInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpCatalogInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCancel)
                    .addComponent(jbtnSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelActionPerformed
        dispose();
}//GEN-LAST:event_jbtnCancelActionPerformed

    private void jbtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveActionPerformed
        if (dirty) {
            book.getInfo().setAuthor(jtfName.getText().trim());
            book.getInfo().setEmail(jtfEmail.getText().trim());
            book.getInfo().setCreated(jdcCreatedOn.getDate());
            dirty = false;
        }

}//GEN-LAST:event_jbtnSaveActionPerformed

private void jdcCreatedOnPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jdcCreatedOnPropertyChange
    if (evt.getPropertyName().equals("date")) {
        dirty = true;
    }
}//GEN-LAST:event_jdcCreatedOnPropertyChange
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnSave;
    private com.toedter.calendar.JDateChooser jdcCreatedOn;
    private javax.swing.JLabel jlblAuthorEmail;
    private javax.swing.JLabel jlblAuthorName;
    private javax.swing.JLabel jlblCreatedOn;
    private javax.swing.JPanel jpCatalogInfo;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfName;
    // End of variables declaration//GEN-END:variables
}
