/*
 * KCookBGui.java
 *
 * Created on 15 de Março de 2008, 18:00
 */
package de.berlios.kcookb.gui;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author  Knitter
 */
public class KCookBGui extends javax.swing.JFrame {

    private KCookBGui me = this;

    /** Creates new form KCookBGui */
    public KCookBGui() {
        initComponents();
    }
    
    private void doQuickSearch(String text) {
        //TODO:
        throw new UnsupportedOperationException("Not implemented yet");
    }
    
    private void openBook() {
        //TODO:
        throw new UnsupportedOperationException("Not implemented yet");
    }
    
    private void save() {
        //TODO:
        throw new UnsupportedOperationException("Not implemented yet");
    }
    
    private void addNewRecipe() {
        //TODO:
        throw new UnsupportedOperationException("Not implemented yet");
    }
    
    private void deleteRecipe() {
        //TODO:
        throw new UnsupportedOperationException("Not implemented yet");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtbMainBar = new javax.swing.JToolBar();
        jbtNewBook = new javax.swing.JButton();
        jbtOpenBook = new javax.swing.JButton();
        jbtSave = new javax.swing.JButton();
        jbtNewRecipe = new javax.swing.JButton();
        jbtDeleteRecipe = new javax.swing.JButton();
        jbtUndo = new javax.swing.JButton();
        jbtRedo = new javax.swing.JButton();
        jbtPrintRecipe = new javax.swing.JButton();
        jtfQuickSearch = new javax.swing.JTextField();
        jbtQuickSearch = new javax.swing.JButton();
        jspMainSplit = new javax.swing.JSplitPane();
        jtpTreeTabs = new javax.swing.JTabbedPane();
        jpTabType = new javax.swing.JPanel();
        jscpTreeTypeScroll = new javax.swing.JScrollPane();
        jtreeType = new javax.swing.JTree();
        jpTabLabel = new javax.swing.JPanel();
        jscpTreeLabelScroll = new javax.swing.JScrollPane();
        jtreeLabel = new javax.swing.JTree();
        jpMainRightPanel = new javax.swing.JPanel();
        jmbMainMenu = new javax.swing.JMenuBar();
        jmFile = new javax.swing.JMenu();
        jmiNewBook = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        jmiOpenBook = new javax.swing.JMenuItem();
        jmiCloseBook = new javax.swing.JMenuItem();
        jmRecentBooks = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JSeparator();
        jmiImport = new javax.swing.JMenuItem();
        jmiExport = new javax.swing.JMenuItem();
        jmiTemplatedBook = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JSeparator();
        jmiExit = new javax.swing.JMenuItem();
        jmRecipe = new javax.swing.JMenu();
        jmHelp = new javax.swing.JMenu();
        jmiHelpContents = new javax.swing.JMenuItem();
        jmiGoOnline = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jmiAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtbMainBar.setFloatable(false);
        jtbMainBar.setRollover(true);

        jbtNewBook.setText("1");
        jbtNewBook.setFocusable(false);
        jbtNewBook.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtNewBook.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtNewBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNewBookActionPerformed(evt);
            }
        });
        jtbMainBar.add(jbtNewBook);

        jbtOpenBook.setText("2");
        jbtOpenBook.setFocusable(false);
        jbtOpenBook.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtOpenBook.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtOpenBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOpenBookActionPerformed(evt);
            }
        });
        jtbMainBar.add(jbtOpenBook);

        jbtSave.setText("3");
        jbtSave.setFocusable(false);
        jbtSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSaveActionPerformed(evt);
            }
        });
        jtbMainBar.add(jbtSave);

        jbtNewRecipe.setText("4");
        jbtNewRecipe.setFocusable(false);
        jbtNewRecipe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtNewRecipe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtNewRecipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNewRecipeActionPerformed(evt);
            }
        });
        jtbMainBar.add(jbtNewRecipe);

        jbtDeleteRecipe.setText("5");
        jbtDeleteRecipe.setFocusable(false);
        jbtDeleteRecipe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtDeleteRecipe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtDeleteRecipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDeleteRecipeActionPerformed(evt);
            }
        });
        jtbMainBar.add(jbtDeleteRecipe);

        jbtUndo.setText("6");
        jbtUndo.setFocusable(false);
        jbtUndo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtUndo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtUndoActionPerformed(evt);
            }
        });
        jtbMainBar.add(jbtUndo);

        jbtRedo.setText("7");
        jbtRedo.setFocusable(false);
        jbtRedo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtRedo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtRedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRedoActionPerformed(evt);
            }
        });
        jtbMainBar.add(jbtRedo);

        jbtPrintRecipe.setText("8");
        jbtPrintRecipe.setFocusable(false);
        jbtPrintRecipe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtPrintRecipe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtPrintRecipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPrintRecipeActionPerformed(evt);
            }
        });
        jtbMainBar.add(jbtPrintRecipe);

        jtfQuickSearch.setMaximumSize(new java.awt.Dimension(150, 20));
        jtfQuickSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfQuickSearchActionPerformed(evt);
            }
        });
        jtbMainBar.add(jtfQuickSearch);

        jbtQuickSearch.setText("9");
        jbtQuickSearch.setFocusable(false);
        jbtQuickSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtQuickSearch.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtQuickSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtQuickSearchActionPerformed(evt);
            }
        });
        jtbMainBar.add(jbtQuickSearch);

        jspMainSplit.setDividerLocation(100);

        jtpTreeTabs.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jscpTreeTypeScroll.setViewportView(jtreeType);

        javax.swing.GroupLayout jpTabTypeLayout = new javax.swing.GroupLayout(jpTabType);
        jpTabType.setLayout(jpTabTypeLayout);
        jpTabTypeLayout.setHorizontalGroup(
            jpTabTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscpTreeTypeScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
        );
        jpTabTypeLayout.setVerticalGroup(
            jpTabTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscpTreeTypeScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        jtpTreeTabs.addTab("tab1", jpTabType);

        jscpTreeLabelScroll.setViewportView(jtreeLabel);

        javax.swing.GroupLayout jpTabLabelLayout = new javax.swing.GroupLayout(jpTabLabel);
        jpTabLabel.setLayout(jpTabLabelLayout);
        jpTabLabelLayout.setHorizontalGroup(
            jpTabLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscpTreeLabelScroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
        );
        jpTabLabelLayout.setVerticalGroup(
            jpTabLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscpTreeLabelScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        jtpTreeTabs.addTab("tab2", jpTabLabel);

        jspMainSplit.setLeftComponent(jtpTreeTabs);

        javax.swing.GroupLayout jpMainRightPanelLayout = new javax.swing.GroupLayout(jpMainRightPanel);
        jpMainRightPanel.setLayout(jpMainRightPanelLayout);
        jpMainRightPanelLayout.setHorizontalGroup(
            jpMainRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );
        jpMainRightPanelLayout.setVerticalGroup(
            jpMainRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        jspMainSplit.setRightComponent(jpMainRightPanel);

        jmFile.setText("File");

        jmiNewBook.setText("New Book ...");
        jmFile.add(jmiNewBook);
        jmFile.add(jSeparator2);

        jmiOpenBook.setText("Open Book");
        jmFile.add(jmiOpenBook);

        jmiCloseBook.setText("Close Book");
        jmFile.add(jmiCloseBook);

        jmRecentBooks.setText("Open Recente");
        jmFile.add(jmRecentBooks);
        jmFile.add(jSeparator3);

        jmiImport.setText("Import ...");
        jmFile.add(jmiImport);

        jmiExport.setText("Export ...");
        jmFile.add(jmiExport);

        jmiTemplatedBook.setText("Export to Template ...");
        jmFile.add(jmiTemplatedBook);
        jmFile.add(jSeparator4);

        jmiExit.setText("Exit");
        jmFile.add(jmiExit);

        jmbMainMenu.add(jmFile);

        jmRecipe.setText("Edit");
        jmbMainMenu.add(jmRecipe);

        jmHelp.setText("Help");

        jmiHelpContents.setText("Help Contents");
        jmiHelpContents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiHelpContentsActionPerformed(evt);
            }
        });
        jmHelp.add(jmiHelpContents);

        jmiGoOnline.setText("Online Reources");
        jmiGoOnline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGoOnlineActionPerformed(evt);
            }
        });
        jmHelp.add(jmiGoOnline);
        jmHelp.add(jSeparator1);

        jmiAbout.setText("About");
        jmiAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAboutActionPerformed(evt);
            }
        });
        jmHelp.add(jmiAbout);

        jmbMainMenu.add(jmHelp);

        setJMenuBar(jmbMainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtbMainBar, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
            .addComponent(jspMainSplit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtbMainBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspMainSplit, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jmiAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAboutActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new About(me, true).setVisible(true);
            }
        });
    }//GEN-LAST:event_jmiAboutActionPerformed

    private void jmiGoOnlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGoOnlineActionPerformed
        //TODO: launch browser with URL to berlios' project page
        //use threads
        throw new UnsupportedOperationException("Not implemented yet");
    }//GEN-LAST:event_jmiGoOnlineActionPerformed

    private void jmiHelpContentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiHelpContentsActionPerformed
        //TODO: Create and add help system
        //use threads
        throw new UnsupportedOperationException("Not implemented yet");
    }//GEN-LAST:event_jmiHelpContentsActionPerformed

    private void jbtNewBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNewBookActionPerformed
        //TODO:
        throw new UnsupportedOperationException("Not implemented yet");
    }//GEN-LAST:event_jbtNewBookActionPerformed

    private void jbtOpenBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtOpenBookActionPerformed
        openBook();
    }//GEN-LAST:event_jbtOpenBookActionPerformed

    private void jbtSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSaveActionPerformed
        save();
    }//GEN-LAST:event_jbtSaveActionPerformed

    private void jbtNewRecipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNewRecipeActionPerformed
        addNewRecipe();
    }//GEN-LAST:event_jbtNewRecipeActionPerformed

    private void jbtDeleteRecipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDeleteRecipeActionPerformed
        deleteRecipe();
    }//GEN-LAST:event_jbtDeleteRecipeActionPerformed

    private void jbtUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtUndoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtUndoActionPerformed

    private void jbtRedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRedoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtRedoActionPerformed

    private void jbtPrintRecipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPrintRecipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtPrintRecipeActionPerformed

    private void jbtQuickSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtQuickSearchActionPerformed
        doQuickSearch(jtfQuickSearch.getText().trim());
    }//GEN-LAST:event_jbtQuickSearchActionPerformed

    private void jtfQuickSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfQuickSearchActionPerformed
        doQuickSearch(jtfQuickSearch.getText().trim());
    }//GEN-LAST:event_jtfQuickSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

            java.awt.EventQueue.invokeLater(new Runnable() {

                public void run() {
                    new KCookBGui().setVisible(true);
                }
            });
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(KCookBGui.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(KCookBGui.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(KCookBGui.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(KCookBGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton jbtDeleteRecipe;
    private javax.swing.JButton jbtNewBook;
    private javax.swing.JButton jbtNewRecipe;
    private javax.swing.JButton jbtOpenBook;
    private javax.swing.JButton jbtPrintRecipe;
    private javax.swing.JButton jbtQuickSearch;
    private javax.swing.JButton jbtRedo;
    private javax.swing.JButton jbtSave;
    private javax.swing.JButton jbtUndo;
    private javax.swing.JMenu jmFile;
    private javax.swing.JMenu jmHelp;
    private javax.swing.JMenu jmRecentBooks;
    private javax.swing.JMenu jmRecipe;
    private javax.swing.JMenuBar jmbMainMenu;
    private javax.swing.JMenuItem jmiAbout;
    private javax.swing.JMenuItem jmiCloseBook;
    private javax.swing.JMenuItem jmiExit;
    private javax.swing.JMenuItem jmiExport;
    private javax.swing.JMenuItem jmiGoOnline;
    private javax.swing.JMenuItem jmiHelpContents;
    private javax.swing.JMenuItem jmiImport;
    private javax.swing.JMenuItem jmiNewBook;
    private javax.swing.JMenuItem jmiOpenBook;
    private javax.swing.JMenuItem jmiTemplatedBook;
    private javax.swing.JPanel jpMainRightPanel;
    private javax.swing.JPanel jpTabLabel;
    private javax.swing.JPanel jpTabType;
    private javax.swing.JScrollPane jscpTreeLabelScroll;
    private javax.swing.JScrollPane jscpTreeTypeScroll;
    private javax.swing.JSplitPane jspMainSplit;
    private javax.swing.JToolBar jtbMainBar;
    private javax.swing.JTextField jtfQuickSearch;
    private javax.swing.JTabbedPane jtpTreeTabs;
    private javax.swing.JTree jtreeLabel;
    private javax.swing.JTree jtreeType;
    // End of variables declaration//GEN-END:variables
}
