/*
 * NewBook.java
 *
 * Created on 27 de Março de 2008, 23:55
 */

package de.berlios.kcookb.gui;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author  Knitter
 */
public class NewBook extends javax.swing.JDialog {
    
    private File selected;
    
    /** Creates new form NewBook */
    public NewBook(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void showCentered() {
        setLocation(getParent().getX() + (getParent().getWidth() / 2) - (getWidth() / 2),
                getParent().getY() + (getParent().getHeight() / 2) - (getHeight() / 2));
        setVisible(true);
    }    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpNewbook = new javax.swing.JPanel();
        jlblNewBook = new javax.swing.JLabel();
        jtfNewBookName = new javax.swing.JTextField();
        jbtBrowse = new javax.swing.JButton();
        jbtnHelp = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();
        jbtnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setUndecorated(true);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/berlios/kcookb/resources/i18n/i18n"); // NOI18N
        jpNewbook.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("NEWBOOKDIALOG_BOXTITLE"))); // NOI18N

        jlblNewBook.setText(bundle.getString("NEWBOOKDIALOG_NAME_LABEL")); // NOI18N

        jbtBrowse.setText(bundle.getString("NewBook.jbtBrowse.text")); // NOI18N
        jbtBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBrowseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpNewbookLayout = new javax.swing.GroupLayout(jpNewbook);
        jpNewbook.setLayout(jpNewbookLayout);
        jpNewbookLayout.setHorizontalGroup(
            jpNewbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNewbookLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblNewBook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNewBookName, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtBrowse))
        );
        jpNewbookLayout.setVerticalGroup(
            jpNewbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNewbookLayout.createSequentialGroup()
                .addGroup(jpNewbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtBrowse)
                    .addComponent(jtfNewBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblNewBook))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbtnHelp.setText(bundle.getString("NEWBOOKDIALOG_HELPBUTTON")); // NOI18N
        jbtnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHelpActionPerformed(evt);
            }
        });

        jbtnCancel.setText(bundle.getString("NEWBOOKDIALOG_CANCELBUTTON")); // NOI18N
        jbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelActionPerformed(evt);
            }
        });

        jbtnOK.setText(bundle.getString("NEWBOOKDIALOG_CREATEBUTTON")); // NOI18N
        jbtnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtnOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnHelp))
                    .addComponent(jpNewbook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbtnCancel, jbtnHelp, jbtnOK});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpNewbook, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnHelp)
                    .addComponent(jbtnCancel)
                    .addComponent(jbtnOK))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHelpActionPerformed
        //TODO: help
}//GEN-LAST:event_jbtnHelpActionPerformed

    private void jbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelActionPerformed
        dispose();
}//GEN-LAST:event_jbtnCancelActionPerformed

    private void jbtnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOKActionPerformed
        ((KCookBGui)getOwner()).newBook(jtfNewBookName.getText());
}//GEN-LAST:event_jbtnOKActionPerformed

    private void jbtBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBrowseActionPerformed
        //TODO: file chooser config
        JFileChooser jfc = new JFileChooser(System.getProperty("user.home"));
        if(jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            selected = jfc.getSelectedFile();
            jtfNewBookName.setText(selected.getAbsolutePath());
        }
    }//GEN-LAST:event_jbtBrowseActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtBrowse;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnHelp;
    private javax.swing.JButton jbtnOK;
    private javax.swing.JLabel jlblNewBook;
    private javax.swing.JPanel jpNewbook;
    private javax.swing.JTextField jtfNewBookName;
    // End of variables declaration//GEN-END:variables
    
}
