/**
 *  Copyright (C) 2008  Sérgio Lopes
 *
 *  This file is part of KCookB.
 *
 *  KCookB is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  KCookB is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with KCookB. If not, see <http://www.gnu.org/licenses/gpl.html>.
 */
package de.berlios.kcookb.gui;

import de.berlios.kcookb.model.Recipe;
import javax.swing.JOptionPane;

/**
 *
 * @author  Knitter
 */
public class RecipeGui extends javax.swing.JDialog {

    private Recipe recipe;
    private RecipeGui me = this;

    /** Creates new form RecipeGui */
    public RecipeGui(java.awt.Frame parent, boolean modal, Recipe recipe) {
        super(parent, modal);
        initComponents();
        this.recipe = recipe;
        if (recipe != null) {
            jtfName.setText(recipe.getTitle());
            recipe.getCooking();
            recipe.getDificulty();
            jspDoses.setValue(recipe.getDoses());
            recipe.getFreazer();
            recipe.getFridge();
            recipe.getIngredients();
            jtaPreparationText.setText(recipe.getMethod());
            recipe.getNote();
            recipe.getPreparation();
            recipe.getPrice();
            recipe.getPrincipal();
            recipe.getRating();
            recipe.getSequence();
            recipe.getTags();
            recipe.getType();
        //TODO: method to populate interface fields with recipe data
        }
    }

    public void showCentered() {
        setLocation(getParent().getX() + (getParent().getWidth() / 2) - (getWidth() / 2),
                getParent().getY() + (getParent().getHeight() / 2) - (getHeight() / 2));
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtpMainTab = new javax.swing.JTabbedPane();
        jpGeneral = new javax.swing.JPanel();
        jtfName = new javax.swing.JTextField();
        jpblName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jcbxDifficulty = new javax.swing.JComboBox();
        jlblDifficulty = new javax.swing.JLabel();
        jlblType = new javax.swing.JLabel();
        jcbxType = new javax.swing.JComboBox();
        jlblPrice = new javax.swing.JLabel();
        jcbxPrice = new javax.swing.JComboBox();
        jlblDoses = new javax.swing.JLabel();
        jspDoses = new javax.swing.JSpinner();
        jlblRatings = new javax.swing.JLabel();
        jspRatings = new javax.swing.JSpinner();
        jlblAddedDate = new javax.swing.JLabel();
        jdcAddedDate = new com.toedter.calendar.JDateChooser();
        jSeparator2 = new javax.swing.JSeparator();
        jlblTimes = new javax.swing.JLabel();
        jlblPreparation = new javax.swing.JLabel();
        jtfPreparation = new javax.swing.JTextField();
        jlblCoocking = new javax.swing.JLabel();
        jtfCoocking = new javax.swing.JTextField();
        jlblTimeLabel1 = new javax.swing.JLabel();
        jlblTimeLabel2 = new javax.swing.JLabel();
        jlblFreezer = new javax.swing.JLabel();
        jtfFreezer = new javax.swing.JTextField();
        jlblTimeLabel3 = new javax.swing.JLabel();
        jlblFridge = new javax.swing.JLabel();
        jtfFridge = new javax.swing.JTextField();
        jlblTimeLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jchkStared = new javax.swing.JCheckBox();
        lblLabels = new javax.swing.JLabel();
        jtfLabels = new javax.swing.JTextField();
        lblLabelsHelp = new javax.swing.JLabel();
        jbtnNotes = new javax.swing.JButton();
        jbtnTips = new javax.swing.JButton();
        jpPreparation = new javax.swing.JPanel();
        jpPreparationSndPanel = new javax.swing.JPanel();
        jscpPreparation = new javax.swing.JScrollPane();
        jtaPreparationText = new javax.swing.JTextArea();
        jpIngredients = new javax.swing.JPanel();
        jpIngredientsSndPanel = new javax.swing.JPanel();
        jbtnAddIngredient = new javax.swing.JButton();
        jbtnRemoveIngredient = new javax.swing.JButton();
        jbtnIngredientUp = new javax.swing.JButton();
        jbtnIngredientDown = new javax.swing.JButton();
        jscpIngredients = new javax.swing.JScrollPane();
        jlstIngredient = new javax.swing.JList();
        jtfIngredientName = new javax.swing.JTextField();
        jlblIngredientName = new javax.swing.JLabel();
        jlblIngredientQuantity = new javax.swing.JLabel();
        jtfIngredientQuantity = new javax.swing.JTextField();
        jpImages = new javax.swing.JPanel();
        jpMainImage = new javax.swing.JPanel();
        jlblMainImage = new javax.swing.JLabel();
        jtfMainImage = new javax.swing.JTextField();
        jbtnMainImage = new javax.swing.JButton();
        jpImageSequence = new javax.swing.JPanel();
        jbtnAddSequence = new javax.swing.JButton();
        jbtnRemoveImageSequence = new javax.swing.JButton();
        jbntImageSequenceUp = new javax.swing.JButton();
        jbtnImageSequenceDown = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlstImageSequence = new javax.swing.JList();
        jbtHelp = new javax.swing.JButton();
        jbtCancel = new javax.swing.JButton();
        jbtSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/berlios/kcookb/resources/i18n/i18n"); // NOI18N
        setTitle(bundle.getString("RecipeGui.title")); // NOI18N

        jtfName.setText(bundle.getString("RecipeGui.jtfName.text")); // NOI18N

        jpblName.setText(bundle.getString("RecipeGui.jpblName.text")); // NOI18N

        jlblDifficulty.setText(bundle.getString("RecipeGui.jlblDifficulty.text")); // NOI18N

        jlblType.setText(bundle.getString("RecipeGui.jlblType.text")); // NOI18N

        jlblPrice.setText(bundle.getString("RecipeGui.jlblPrice.text")); // NOI18N

        jlblDoses.setText(bundle.getString("RecipeGui.jlblDoses.text")); // NOI18N

        jlblRatings.setText(bundle.getString("RecipeGui.jlblRatings.text")); // NOI18N

        jlblAddedDate.setText(bundle.getString("RecipeGui.jlblAddedDate.text")); // NOI18N

        jlblTimes.setText(bundle.getString("RecipeGui.jlblTimes.text")); // NOI18N

        jlblPreparation.setText(bundle.getString("RecipeGui.jlblPreparation.text")); // NOI18N

        jtfPreparation.setText(bundle.getString("RecipeGui.jtfPreparation.text")); // NOI18N

        jlblCoocking.setText(bundle.getString("RecipeGui.jlblCoocking.text")); // NOI18N

        jtfCoocking.setText(bundle.getString("RecipeGui.jtfCoocking.text")); // NOI18N

        jlblTimeLabel1.setText(bundle.getString("RecipeGui.jlblTimeLabel1.text")); // NOI18N

        jlblTimeLabel2.setText(bundle.getString("RecipeGui.jlblTimeLabel2.text")); // NOI18N

        jlblFreezer.setText(bundle.getString("RecipeGui.jlblFreezer.text")); // NOI18N

        jtfFreezer.setText(bundle.getString("RecipeGui.jtfFreezer.text")); // NOI18N

        jlblTimeLabel3.setText(bundle.getString("RecipeGui.jlblTimeLabel3.text")); // NOI18N

        jlblFridge.setText(bundle.getString("RecipeGui.jlblFridge.text")); // NOI18N

        jtfFridge.setText(bundle.getString("RecipeGui.jtfFridge.text")); // NOI18N

        jlblTimeLabel4.setText(bundle.getString("RecipeGui.jlblTimeLabel4.text")); // NOI18N

        jchkStared.setText(bundle.getString("RecipeGui.jchkStared.text")); // NOI18N

        lblLabels.setText(bundle.getString("RecipeGui.lblLabels.text")); // NOI18N

        jtfLabels.setText(bundle.getString("RecipeGui.jtfLabels.text")); // NOI18N

        lblLabelsHelp.setText(bundle.getString("RecipeGui.lblLabelsHelp.text")); // NOI18N

        jbtnNotes.setText(bundle.getString("RecipeGui.jbtnNotes.text")); // NOI18N
        jbtnNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNotesActionPerformed(evt);
            }
        });

        jbtnTips.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/berlios/kcookb/resources/images/x16/mn-tips.png"))); // NOI18N
        jbtnTips.setText(bundle.getString("RecipeGui.jbtnTips.text")); // NOI18N
        jbtnTips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTipsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpGeneralLayout = new javax.swing.GroupLayout(jpGeneral);
        jpGeneral.setLayout(jpGeneralLayout);
        jpGeneralLayout.setHorizontalGroup(
            jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpGeneralLayout.createSequentialGroup()
                        .addComponent(jlblTimes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addGroup(jpGeneralLayout.createSequentialGroup()
                        .addComponent(jpblName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfName, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE))
                    .addGroup(jpGeneralLayout.createSequentialGroup()
                        .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblDoses)
                            .addComponent(jlblDifficulty))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jcbxDifficulty, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jspDoses, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblRatings)
                            .addComponent(jlblType, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbxType, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jspRatings))
                        .addGap(18, 18, 18)
                        .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblPrice)
                            .addComponent(jlblAddedDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcbxPrice, 0, 122, Short.MAX_VALUE)
                            .addComponent(jdcAddedDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)))
                    .addGroup(jpGeneralLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpGeneralLayout.createSequentialGroup()
                                .addComponent(jlblPreparation)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfPreparation, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlblTimeLabel1))
                            .addGroup(jpGeneralLayout.createSequentialGroup()
                                .addComponent(jlblFreezer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfFreezer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlblTimeLabel3)))
                        .addGap(18, 18, 18)
                        .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblCoocking)
                            .addComponent(jlblFridge))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfFridge)
                            .addComponent(jtfCoocking, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblTimeLabel2)
                            .addComponent(jlblTimeLabel4)))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addGroup(jpGeneralLayout.createSequentialGroup()
                        .addComponent(lblLabels)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfLabels, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                            .addComponent(lblLabelsHelp)
                            .addComponent(jchkStared)))
                    .addGroup(jpGeneralLayout.createSequentialGroup()
                        .addComponent(jbtnNotes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnTips)))
                .addContainerGap())
        );
        jpGeneralLayout.setVerticalGroup(
            jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpblName)
                    .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblDifficulty)
                    .addComponent(jlblType)
                    .addComponent(jlblPrice)
                    .addComponent(jcbxPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbxDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlblDoses)
                        .addComponent(jspDoses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlblRatings)
                        .addComponent(jspRatings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlblAddedDate))
                    .addComponent(jdcAddedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblTimes)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblPreparation)
                    .addComponent(jtfPreparation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTimeLabel1)
                    .addComponent(jlblCoocking)
                    .addComponent(jtfCoocking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTimeLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblFreezer)
                    .addComponent(jlblTimeLabel3)
                    .addComponent(jtfFreezer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblFridge)
                    .addComponent(jtfFridge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTimeLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfLabels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLabels))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLabelsHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jchkStared)
                .addGap(18, 18, 18)
                .addGroup(jpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNotes)
                    .addComponent(jbtnTips))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jtpMainTab.addTab(bundle.getString("RecipeGui.jpGeneral.TabConstraints.tabTitle"), jpGeneral); // NOI18N

        jpPreparationSndPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("RecipeGui.jpPreparationSndPanel.border.title"))); // NOI18N

        jtaPreparationText.setColumns(20);
        jtaPreparationText.setRows(5);
        jscpPreparation.setViewportView(jtaPreparationText);

        javax.swing.GroupLayout jpPreparationSndPanelLayout = new javax.swing.GroupLayout(jpPreparationSndPanel);
        jpPreparationSndPanel.setLayout(jpPreparationSndPanelLayout);
        jpPreparationSndPanelLayout.setHorizontalGroup(
            jpPreparationSndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPreparationSndPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jscpPreparation, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpPreparationSndPanelLayout.setVerticalGroup(
            jpPreparationSndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPreparationSndPanelLayout.createSequentialGroup()
                .addComponent(jscpPreparation, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpPreparationLayout = new javax.swing.GroupLayout(jpPreparation);
        jpPreparation.setLayout(jpPreparationLayout);
        jpPreparationLayout.setHorizontalGroup(
            jpPreparationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPreparationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPreparationSndPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpPreparationLayout.setVerticalGroup(
            jpPreparationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPreparationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPreparationSndPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtpMainTab.addTab(bundle.getString("RecipeGui.jpPreparation.TabConstraints.tabTitle"), jpPreparation); // NOI18N

        jpIngredientsSndPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("RecipeGui.jpIngredientsSndPanel.border.title"))); // NOI18N

        jbtnAddIngredient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/berlios/kcookb/resources/images/x22/tb-add.png"))); // NOI18N
        jbtnAddIngredient.setText(bundle.getString("RecipeGui.jbtnAddIngredient.text")); // NOI18N
        jbtnAddIngredient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddIngredientActionPerformed(evt);
            }
        });

        jbtnRemoveIngredient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/berlios/kcookb/resources/images/x22/tb-remove.png"))); // NOI18N
        jbtnRemoveIngredient.setText(bundle.getString("RecipeGui.jbtnRemoveIngredient.text")); // NOI18N
        jbtnRemoveIngredient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveIngredientActionPerformed(evt);
            }
        });

        jbtnIngredientUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/berlios/kcookb/resources/images/x22/tb-up.png"))); // NOI18N
        jbtnIngredientUp.setText(bundle.getString("RecipeGui.jbtnIngredientUp.text")); // NOI18N
        jbtnIngredientUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIngredientUpActionPerformed(evt);
            }
        });

        jbtnIngredientDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/berlios/kcookb/resources/images/x22/tb-down.png"))); // NOI18N
        jbtnIngredientDown.setText(bundle.getString("RecipeGui.jbtnIngredientDown.text")); // NOI18N
        jbtnIngredientDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIngredientDownActionPerformed(evt);
            }
        });

        jscpIngredients.setViewportView(jlstIngredient);

        jtfIngredientName.setText(bundle.getString("RecipeGui.jtfIngredientName.text")); // NOI18N

        jlblIngredientName.setText(bundle.getString("RecipeGui.jlblIngredientName.text")); // NOI18N

        jlblIngredientQuantity.setText(bundle.getString("RecipeGui.jlblIngredientQuantity.text")); // NOI18N

        jtfIngredientQuantity.setText(bundle.getString("RecipeGui.jtfIngredientQuantity.text")); // NOI18N

        javax.swing.GroupLayout jpIngredientsSndPanelLayout = new javax.swing.GroupLayout(jpIngredientsSndPanel);
        jpIngredientsSndPanel.setLayout(jpIngredientsSndPanelLayout);
        jpIngredientsSndPanelLayout.setHorizontalGroup(
            jpIngredientsSndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIngredientsSndPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpIngredientsSndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpIngredientsSndPanelLayout.createSequentialGroup()
                        .addComponent(jlblIngredientName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfIngredientName, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlblIngredientQuantity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfIngredientQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                    .addComponent(jscpIngredients, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpIngredientsSndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbtnAddIngredient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnRemoveIngredient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnIngredientDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnIngredientUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpIngredientsSndPanelLayout.setVerticalGroup(
            jpIngredientsSndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIngredientsSndPanelLayout.createSequentialGroup()
                .addComponent(jbtnAddIngredient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnRemoveIngredient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnIngredientUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnIngredientDown)
                .addContainerGap(178, Short.MAX_VALUE))
            .addGroup(jpIngredientsSndPanelLayout.createSequentialGroup()
                .addGroup(jpIngredientsSndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblIngredientName)
                    .addComponent(jtfIngredientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblIngredientQuantity)
                    .addComponent(jtfIngredientQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jscpIngredients, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpIngredientsLayout = new javax.swing.GroupLayout(jpIngredients);
        jpIngredients.setLayout(jpIngredientsLayout);
        jpIngredientsLayout.setHorizontalGroup(
            jpIngredientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIngredientsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpIngredientsSndPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpIngredientsLayout.setVerticalGroup(
            jpIngredientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIngredientsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpIngredientsSndPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtpMainTab.addTab(bundle.getString("RecipeGui.jpIngredients.TabConstraints.tabTitle"), jpIngredients); // NOI18N

        jpMainImage.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("RecipeGui.jpMainImage.border.title"))); // NOI18N

        jlblMainImage.setText(bundle.getString("RecipeGui.jlblMainImage.text")); // NOI18N

        jtfMainImage.setText(bundle.getString("RecipeGui.jtfMainImage.text")); // NOI18N

        jbtnMainImage.setText(bundle.getString("RecipeGui.jbtnMainImage.text")); // NOI18N
        jbtnMainImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMainImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMainImageLayout = new javax.swing.GroupLayout(jpMainImage);
        jpMainImage.setLayout(jpMainImageLayout);
        jpMainImageLayout.setHorizontalGroup(
            jpMainImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMainImageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblMainImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfMainImage, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnMainImage)
                .addContainerGap())
        );
        jpMainImageLayout.setVerticalGroup(
            jpMainImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMainImageLayout.createSequentialGroup()
                .addGroup(jpMainImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblMainImage)
                    .addComponent(jbtnMainImage)
                    .addComponent(jtfMainImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jpImageSequence.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("RecipeGui.jpImageSequence.border.title"))); // NOI18N

        jbtnAddSequence.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/berlios/kcookb/resources/images/x22/tb-add.png"))); // NOI18N
        jbtnAddSequence.setText(bundle.getString("RecipeGui.jbtnAddSequence.text")); // NOI18N
        jbtnAddSequence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddSequenceActionPerformed(evt);
            }
        });

        jbtnRemoveImageSequence.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/berlios/kcookb/resources/images/x22/tb-remove.png"))); // NOI18N
        jbtnRemoveImageSequence.setText(bundle.getString("RecipeGui.jbtnRemoveImageSequence.text")); // NOI18N
        jbtnRemoveImageSequence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveImageSequenceActionPerformed(evt);
            }
        });

        jbntImageSequenceUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/berlios/kcookb/resources/images/x22/tb-up.png"))); // NOI18N
        jbntImageSequenceUp.setText(bundle.getString("RecipeGui.jbntImageSequenceUp.text")); // NOI18N
        jbntImageSequenceUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbntImageSequenceUpActionPerformed(evt);
            }
        });

        jbtnImageSequenceDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/berlios/kcookb/resources/images/x22/tb-down.png"))); // NOI18N
        jbtnImageSequenceDown.setText(bundle.getString("RecipeGui.jbtnImageSequenceDown.text")); // NOI18N
        jbtnImageSequenceDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnImageSequenceDownActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jlstImageSequence);

        javax.swing.GroupLayout jpImageSequenceLayout = new javax.swing.GroupLayout(jpImageSequence);
        jpImageSequence.setLayout(jpImageSequenceLayout);
        jpImageSequenceLayout.setHorizontalGroup(
            jpImageSequenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpImageSequenceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpImageSequenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpImageSequenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jbtnAddSequence)
                        .addComponent(jbtnRemoveImageSequence)
                        .addComponent(jbntImageSequenceUp))
                    .addComponent(jbtnImageSequenceDown, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jpImageSequenceLayout.setVerticalGroup(
            jpImageSequenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpImageSequenceLayout.createSequentialGroup()
                .addGroup(jpImageSequenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpImageSequenceLayout.createSequentialGroup()
                        .addComponent(jbtnAddSequence)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnRemoveImageSequence)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbntImageSequenceUp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnImageSequenceDown))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jpImagesLayout = new javax.swing.GroupLayout(jpImages);
        jpImages.setLayout(jpImagesLayout);
        jpImagesLayout.setHorizontalGroup(
            jpImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpImagesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpMainImage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpImageSequence, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpImagesLayout.setVerticalGroup(
            jpImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpImagesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpMainImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpImageSequence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtpMainTab.addTab(bundle.getString("RecipeGui.jpImages.TabConstraints.tabTitle"), jpImages); // NOI18N

        jbtHelp.setText(bundle.getString("RecipeGui.jbtHelp.text")); // NOI18N
        jbtHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtHelpActionPerformed(evt);
            }
        });

        jbtCancel.setText(bundle.getString("RecipeGui.jbtCancel.text")); // NOI18N
        jbtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelActionPerformed(evt);
            }
        });

        jbtSave.setText(bundle.getString("RecipeGui.jbtSave.text")); // NOI18N
        jbtSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpMainTab, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(378, Short.MAX_VALUE)
                .addComponent(jbtSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtHelp)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbtCancel, jbtHelp, jbtSave});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtpMainTab, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtHelp)
                    .addComponent(jbtCancel)
                    .addComponent(jbtSave))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSaveActionPerformed
        String title = jtfName.getText().trim();
        String method = jtaPreparationText.getText().trim();
        String cooking = jtfCoocking.getText().trim();
        String preparation = jtfPreparation.getText().trim();
        /*recipe = new Recipe(
        title, 
        preparation, 
        cooking, 
        dificulty, 
        price, 
        ingredients, 
        type, 
        WIDTH, 
        sequence, 
        principal, 
        note, 
        tips, 
        WIDTH, 
        rootPaneCheckingEnabled, 
        tags, 
        method, 
        freazer, 
        fridge)*/
        dispose();
    }//GEN-LAST:event_jbtSaveActionPerformed

    private void jbtCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelActionPerformed
        dispose();
    }//GEN-LAST:event_jbtCancelActionPerformed

    private void jbtHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtHelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtHelpActionPerformed

private void jbtnAddIngredientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddIngredientActionPerformed
    JOptionPane.showInputDialog("");
}//GEN-LAST:event_jbtnAddIngredientActionPerformed

private void jbtnRemoveIngredientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveIngredientActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jbtnRemoveIngredientActionPerformed

private void jbtnIngredientUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIngredientUpActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jbtnIngredientUpActionPerformed

private void jbtnIngredientDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIngredientDownActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jbtnIngredientDownActionPerformed

private void jbtnMainImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMainImageActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jbtnMainImageActionPerformed

private void jbtnAddSequenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddSequenceActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jbtnAddSequenceActionPerformed

private void jbtnRemoveImageSequenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveImageSequenceActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jbtnRemoveImageSequenceActionPerformed

private void jbntImageSequenceUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbntImageSequenceUpActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jbntImageSequenceUpActionPerformed

private void jbtnImageSequenceDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnImageSequenceDownActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jbtnImageSequenceDownActionPerformed

private void jbtnTipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTipsActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jbtnTipsActionPerformed

private void jbtnNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNotesActionPerformed
    java.awt.EventQueue.invokeLater(new Runnable() {

        public void run() {
            new NoteDialog(me, true, recipe != null ? recipe.getNote() : null).showCentered();
        }
    });
}//GEN-LAST:event_jbtnNotesActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbntImageSequenceUp;
    private javax.swing.JButton jbtCancel;
    private javax.swing.JButton jbtHelp;
    private javax.swing.JButton jbtSave;
    private javax.swing.JButton jbtnAddIngredient;
    private javax.swing.JButton jbtnAddSequence;
    private javax.swing.JButton jbtnImageSequenceDown;
    private javax.swing.JButton jbtnIngredientDown;
    private javax.swing.JButton jbtnIngredientUp;
    private javax.swing.JButton jbtnMainImage;
    private javax.swing.JButton jbtnNotes;
    private javax.swing.JButton jbtnRemoveImageSequence;
    private javax.swing.JButton jbtnRemoveIngredient;
    private javax.swing.JButton jbtnTips;
    private javax.swing.JComboBox jcbxDifficulty;
    private javax.swing.JComboBox jcbxPrice;
    private javax.swing.JComboBox jcbxType;
    private javax.swing.JCheckBox jchkStared;
    private com.toedter.calendar.JDateChooser jdcAddedDate;
    private javax.swing.JLabel jlblAddedDate;
    private javax.swing.JLabel jlblCoocking;
    private javax.swing.JLabel jlblDifficulty;
    private javax.swing.JLabel jlblDoses;
    private javax.swing.JLabel jlblFreezer;
    private javax.swing.JLabel jlblFridge;
    private javax.swing.JLabel jlblIngredientName;
    private javax.swing.JLabel jlblIngredientQuantity;
    private javax.swing.JLabel jlblMainImage;
    private javax.swing.JLabel jlblPreparation;
    private javax.swing.JLabel jlblPrice;
    private javax.swing.JLabel jlblRatings;
    private javax.swing.JLabel jlblTimeLabel1;
    private javax.swing.JLabel jlblTimeLabel2;
    private javax.swing.JLabel jlblTimeLabel3;
    private javax.swing.JLabel jlblTimeLabel4;
    private javax.swing.JLabel jlblTimes;
    private javax.swing.JLabel jlblType;
    private javax.swing.JList jlstImageSequence;
    private javax.swing.JList jlstIngredient;
    private javax.swing.JPanel jpGeneral;
    private javax.swing.JPanel jpImageSequence;
    private javax.swing.JPanel jpImages;
    private javax.swing.JPanel jpIngredients;
    private javax.swing.JPanel jpIngredientsSndPanel;
    private javax.swing.JPanel jpMainImage;
    private javax.swing.JPanel jpPreparation;
    private javax.swing.JPanel jpPreparationSndPanel;
    private javax.swing.JLabel jpblName;
    private javax.swing.JScrollPane jscpIngredients;
    private javax.swing.JScrollPane jscpPreparation;
    private javax.swing.JSpinner jspDoses;
    private javax.swing.JSpinner jspRatings;
    private javax.swing.JTextArea jtaPreparationText;
    private javax.swing.JTextField jtfCoocking;
    private javax.swing.JTextField jtfFreezer;
    private javax.swing.JTextField jtfFridge;
    private javax.swing.JTextField jtfIngredientName;
    private javax.swing.JTextField jtfIngredientQuantity;
    private javax.swing.JTextField jtfLabels;
    private javax.swing.JTextField jtfMainImage;
    private javax.swing.JTextField jtfName;
    private javax.swing.JTextField jtfPreparation;
    private javax.swing.JTabbedPane jtpMainTab;
    private javax.swing.JLabel lblLabels;
    private javax.swing.JLabel lblLabelsHelp;
    // End of variables declaration//GEN-END:variables
}
