/*
 * TemplateExport.java
 *
 * Created on 15 de Março de 2008, 18:01
 */
package de.berlios.kcookb.gui;

import javax.swing.JFileChooser;

/**
 *
 * @author  Knitter
 */
public class TemplateExport extends javax.swing.JDialog {

    /** Creates new form TemplateExport */
    public TemplateExport(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void showCentered() {
        setLocation(getParent().getX() + (getParent().getWidth() / 2) - (getWidth() / 2),
                getParent().getY() + (getParent().getHeight() / 2) - (getHeight() / 2));
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTemplates = new javax.swing.JPanel();
        jscpTemplates = new javax.swing.JScrollPane();
        jlstTemplates = new javax.swing.JList();
        jpOptions = new javax.swing.JPanel();
        jpPreview = new javax.swing.JPanel();
        jlblPreview = new javax.swing.JLabel();
        jlblName = new javax.swing.JLabel();
        jtfName = new javax.swing.JTextField();
        jlblExportTo = new javax.swing.JLabel();
        jtfExportTo = new javax.swing.JTextField();
        jbtBrowse = new javax.swing.JButton();
        jchkOpenAfterExport = new javax.swing.JCheckBox();
        jbtHelp = new javax.swing.JButton();
        jbtCancel = new javax.swing.JButton();
        jbtExport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("null");
        setResizable(false);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/berlios/kcookb/gui/Bundle"); // NOI18N
        jpTemplates.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("TEMPLATEEXPORTDIALOG_TEMPLATESBORDER"))); // NOI18N

        jlstTemplates.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jlstTemplates.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jlstTemplatesValueChanged(evt);
            }
        });
        jscpTemplates.setViewportView(jlstTemplates);

        javax.swing.GroupLayout jpTemplatesLayout = new javax.swing.GroupLayout(jpTemplates);
        jpTemplates.setLayout(jpTemplatesLayout);
        jpTemplatesLayout.setHorizontalGroup(
            jpTemplatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscpTemplates, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
        );
        jpTemplatesLayout.setVerticalGroup(
            jpTemplatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscpTemplates, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
        );

        java.util.ResourceBundle bundle1 = java.util.ResourceBundle.getBundle("de/berlios/kcookb/resources/i18n/i18n"); // NOI18N
        jpOptions.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle1.getString("TEMPLATEEXPORTDIALOG_OPTIONSBORDER"))); // NOI18N

        jpPreview.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle1.getString("TEMPLATEEXPORTDIALOG_PREVIEWBORDER"))); // NOI18N

        jlblPreview.setText(bundle1.getString("TemplateExport.jlblPreview.text")); // NOI18N

        javax.swing.GroupLayout jpPreviewLayout = new javax.swing.GroupLayout(jpPreview);
        jpPreview.setLayout(jpPreviewLayout);
        jpPreviewLayout.setHorizontalGroup(
            jpPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlblPreview, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
        );
        jpPreviewLayout.setVerticalGroup(
            jpPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlblPreview, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
        );

        jlblName.setText(bundle1.getString("TEMPLATEEXPORTDIALOG_LABELNAME")); // NOI18N

        jlblExportTo.setText(bundle1.getString("TEMPLATEEXPORTDIALOG_LABELEXPORTTO")); // NOI18N

        jbtBrowse.setText(bundle1.getString("TemplateExport.jbtBrowse.text")); // NOI18N
        jbtBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBrowseActionPerformed(evt);
            }
        });

        jchkOpenAfterExport.setText(bundle1.getString("TEMPLATEEXPORTDIALOG_OPENAFTEREXPORT")); // NOI18N

        javax.swing.GroupLayout jpOptionsLayout = new javax.swing.GroupLayout(jpOptions);
        jpOptions.setLayout(jpOptionsLayout);
        jpOptionsLayout.setHorizontalGroup(
            jpOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpPreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpOptionsLayout.createSequentialGroup()
                        .addGroup(jpOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblName)
                            .addComponent(jlblExportTo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jchkOpenAfterExport)
                            .addGroup(jpOptionsLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addGroup(jpOptionsLayout.createSequentialGroup()
                                        .addComponent(jtfExportTo, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtBrowse)))))))
                .addContainerGap())
        );
        jpOptionsLayout.setVerticalGroup(
            jpOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOptionsLayout.createSequentialGroup()
                .addComponent(jpPreview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblName)
                    .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtBrowse)
                    .addComponent(jlblExportTo)
                    .addComponent(jtfExportTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jchkOpenAfterExport)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jbtHelp.setText(bundle1.getString("TEMPLATEEXPORTDIALOG_HELPBUTTON")); // NOI18N
        jbtHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtHelpActionPerformed(evt);
            }
        });

        jbtCancel.setText(bundle1.getString("TEMPLATEEXPORTDIALOG_CANCELBUTTON")); // NOI18N
        jbtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelActionPerformed(evt);
            }
        });

        jbtExport.setText(bundle1.getString("TEMPLATEEXPORTDIALOG_EXPORTBUTTON")); // NOI18N
        jbtExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpTemplates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtExport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtHelp)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jpTemplates, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpOptions, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtHelp)
                    .addComponent(jbtCancel)
                    .addComponent(jbtExport))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBrowseActionPerformed
        JFileChooser jfc = new JFileChooser(System.getProperty("user.home"));
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if(jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            //TODO:
        }
        
    }//GEN-LAST:event_jbtBrowseActionPerformed

    private void jbtExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExportActionPerformed
        //TODO: export, open destination and save
    }//GEN-LAST:event_jbtExportActionPerformed

    private void jbtCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelActionPerformed
        dispose();
    }//GEN-LAST:event_jbtCancelActionPerformed

    private void jbtHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtHelpActionPerformed
        //TODO: help for template export dialog
    }//GEN-LAST:event_jbtHelpActionPerformed

    private void jlstTemplatesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jlstTemplatesValueChanged
        //TODO: change values in the details panel
    }//GEN-LAST:event_jlstTemplatesValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtBrowse;
    private javax.swing.JButton jbtCancel;
    private javax.swing.JButton jbtExport;
    private javax.swing.JButton jbtHelp;
    private javax.swing.JCheckBox jchkOpenAfterExport;
    private javax.swing.JLabel jlblExportTo;
    private javax.swing.JLabel jlblName;
    private javax.swing.JLabel jlblPreview;
    private javax.swing.JList jlstTemplates;
    private javax.swing.JPanel jpOptions;
    private javax.swing.JPanel jpPreview;
    private javax.swing.JPanel jpTemplates;
    private javax.swing.JScrollPane jscpTemplates;
    private javax.swing.JTextField jtfExportTo;
    private javax.swing.JTextField jtfName;
    // End of variables declaration//GEN-END:variables
}
